### ISSUE TITLE
Invalid parameters schema keywords location

### ISSUE THREAD

**Issue by nxht** [elysiajs/elysia-swagger#102]
Based on
- https://swagger.io/docs/specification/describing-parameters/
- https://swagger.io/specification/#parameter-object
- https://swagger.io/docs/specification/data-models/keywords/

The schema [keywords](https://swagger.io/docs/specification/data-models/keywords/) should go under `schema` key.

Example code: 
```ts
import swagger from '@elysiajs/swagger';
import { Elysia, t } from 'elysia';

const app = new Elysia()
  .use(swagger())
  .get('/', async () => 'hi', {
    query: t.Object({
      a: t.Optional(t.String({
        title: 'title',
        enum: ['a', 'b'],
        pattern: 'a|b',
        default: 'b',
        minLength: 1,
        maxLength: 10,
      })),
    }),
  })
  .listen(3000);

console.log(
  `🦊 Elysia is running at http://${app.server?.hostname}:${app.server?.port}`,
);
```

Current parameter json
```json
{
  "parameters": [
    {
      "title": "title",
      "enum": [
        "a",
        "b"
      ],
      "pattern": "a|b",
      "default": "b",
      "minLength": 1,
      "maxLength": 10,
      "schema": {
        "type": "string"
      },
      "in": "query",
      "name": "a",
      "required": false
    }
  ]
}
```

Expected parameter json
```json
{
  "parameters": [
    {
      "schema": {
        "title": "title",
        "enum": [
          "a",
          "b"
        ],
        "pattern": "a|b",
        "default": "b",
        "minLength": 1,
        "maxLength": 10,
        "type": "string"
      },
      "in": "query",
      "name": "a",
      "required": false
    }
  ]
}
```

**Comment by nxht** [comment]
- Found #41 seems to be similar issue
  - And #50 do fixes the issue, though it moves non-schema keywords under schema as well
  - And commits after moves out the non-schema keywords except `type`, causing the issue to be happening again

**Comment by rivulent** [comment]
ETA on merging this PR? I tested in my application and found that it solved my pain points.

**Comment by marclave** [comment]
> ETA on merging this PR? I tested in my application and found that it solved my pain points.

merged! ✨
