### ISSUE TITLE
Swagger does not generate documentation if path is set to the home directory.

### ISSUE THREAD

**Issue by akainocode** [elysiajs/elysia-swagger#115]
Swagger doesn't appear to generate documentation if the path is set to '/', an example here:
```ts
import { Elysia } from 'elysia';
import { swagger } from '@elysiajs/swagger'

const app = new Elysia()
  .use(swagger({
    path: '/',
    documentation : {
      tags : [
        { name: 'tag1', description: 'desc1'},
      ]
    }
  }))
  .get('/test', () => "Test", {
    detail : {
      tags: ['tag1']
    } 
  })
  .listen(3000)
```

The above only generates the background page for the swagger documentation, while if you adjust the path parameter to anything else or even remove it, it appears to work.

I can write a workaround to achieve the intended effect, but it does appear to be a bug.

**Comment by marclave** [comment]
got a PR open :) 

https://github.com/elysiajs/elysia-swagger/pull/118

**Comment by akainocode** [comment]
Thank you! I'll close this issue once it gets merged.
