### ISSUE TITLE
No endpoints in definition when using `aot: false`

### ISSUE THREAD

**Issue by samuba** [elysiajs/elysia-swagger#12]
I would love to use this on cloudflare but when I configure elysia with `aot: false` it will not generate the endpoints in the swagger definition.

Is this a fundamental caveat of using dynamic mode because types and endpoints can not be inferred without this step, or is there a way to make it work with dynamic mode?

See also discussion here: https://github.com/elysiajs/elysia/issues/58

**Comment by SaltyAom** [comment]
Seems like this is a bug, should be fixed by updating Elysia 0.6.8

**Comment by samuel-bach** [comment]
You are right it works with newest Elysia version. Awesome 🙌

**Comment by samuba** [comment]
You are right this is fixed with newest Elysia version. Awesome 🙌

**Comment by samuba** [comment]
You are right this is fixed with newest Elysia version. Awesome 🙌
