### ISSUE TITLE
Swagger not showing prettified json

### ISSUE THREAD

**Issue by kulterryan** [elysiajs/elysia-swagger#126]
Suddenly my Swagger docs started showing non-formatted data in the responses: 

![image](https://github.com/elysiajs/elysia-swagger/assets/36154235/59529db9-e8b8-4244-aa96-907109390d93)

Previously it was working fine though, we've checked all the changes made recently, but no clues.

**Comment by marclave** [comment]
hi @kulterryan ! we have a fix coming very shortly :)

**Comment by marclave** [comment]
@kulterryan in this list https://github.com/scalar/scalar/pull/2113

**Comment by marclave** [comment]
hey @kulterryan could you hard refresh? just did a release and it's fixed (i pulled and tested) :) 

<img width="558" alt="image" src="https://github.com/elysiajs/elysia-swagger/assets/6176314/e0e75cea-1342-453c-9a30-527c309fef9b">

**Comment by kulterryan** [comment]
Hi @marclave, the issue still persists on my end!

**Comment by marclave** [comment]
> Hi @marclave, the issue still persists on my end!

@kulterryan would you be able to share a screenshot of the version of scalar you're running? :)

**Comment by kulterryan** [comment]
@marclave thanks, updating the version resolved the issue.
