### ISSUE TITLE
Path descriptions

### ISSUE THREAD

**Issue by crishoj** [elysiajs/elysia-swagger#13]
Is somehow possible to include descriptions for the paths in the generated docs, e.g. from docblock/comments?

**Comment by crishoj** [comment]
> Do you mean the description on the title of the endpoint?

Exactly. 

I'm using the following to generate docs from endpoint schemas:

```ts
const app = new Elysia()
    .use(swagger({
        path: '/docs',
        documentation: {info: {title: 'App title', version: '0.1'}}
    }))
```

I get "bare" documentation with expected parameter types (which is great), but would like to add descriptions as well:

![image](https://github.com/elysiajs/elysia-swagger/assets/20393/f8000bd1-f145-486d-a9ef-6f0a03a1feb4)

**Comment by igrschmidt** [comment]
```typescript
  app.get(
    `/${provider.slug}`,
    async () => {
      const data = await provider.fetchName(provider.id, provider.name);
      return {
        ...data,
        draw_date: data.draw_date.toISOString(),
      };
    },
    {
      response: {
        200: t.Object(getSchemaBySlug(provider.slug)),
      },
      type: "application/json",
      detail: {
        summary: `Gets details of a specific ${provider.name} draw.`,
        tags: ["Lottery Results"],
      },
    }
  );
``` 

That's how I did it on mine. Is actually set on each individual endpoint, under the `detail` object.

**Comment by crishoj** [comment]
Just what I had in mind — thanks!
