### ISSUE TITLE
expose swagger json as an endpoint on the serve

### ISSUE THREAD

**Issue by vreallyla** [elysiajs/elysia-swagger#143]
Is it possible to create an endpoint in ElysiaJS that serves the Swagger JSON documentation, for example, at `/swagger.json`?

**Comment by dhkatz** [comment]
You can access the raw OpenAPI spec at `/swagger/json`. Is that not what you are looking for?

**Comment by vreallyla** [comment]
> You can access the raw OpenAPI spec at `/swagger/json`. Is that not what you are looking for?

Yes, that's what I was looking for. I found it a few days ago. Thank you for your attention.
