### ISSUE TITLE
Hide Open API Client Button

### ISSUE THREAD

**Issue by andrefelipeschulle** [elysiajs/elysia-swagger#170]
Is there any way to hide the "Open API Client" button?

<img width="338" alt="Captura de Tela 2024-11-14 às 11 15 13" src="https://github.com/user-attachments/assets/85440cb5-4d5b-45ad-afa5-3c24e54f4407">

<img width="493" alt="Captura de Tela 2024-11-14 às 11 15 26" src="https://github.com/user-attachments/assets/2a9587ae-7262-43ee-8dc2-0163e5b420cb">

**Comment by dodas** [comment]
You can do so with CSS:
```ts
new Elysia().use(
  swagger({
    scalarConfig: {
      customCss: `.open-api-client-button { display: none !important }`,
    },
  })
)
