### ISSUE TITLE
Most OpenAPI gen. tools require `operationId` to be set for function properly

### ISSUE THREAD

**Issue by JulianCataldo** [elysiajs/elysia-swagger#5]
Hello! THANKS for making this, I love Elysia API, best I've seen for a web server so far!

---

3 generators tested, and none are working because`operationId`😔 is mandatory for them.

Here,

https://github.com/elysiajs/elysia-swagger/blob/959f2328902195b0476dcd6e659d217c2def6649/src/utils.ts#L25

adding a:

`method.operationId = "…"`

With two possible strategies I can think of:

1. Auto-generating name from path

<kbd>DELETE</kbd>  `/document/{id}` > `deleteDocumentById`

cool for simple cases, but complicated with `/document/{id}/stuff/foo/{bar}`  > `deleteDocumentByIdStuffFooByBar` lol

2. Using decorators

`.decorateApi("operationId", "foobar")`

`.decorateApi("description", "my cool op.")`

Wha d'ya think?

Cheers.

**Comment by SaltyAom** [comment]
Hi, thanks for pointing this out, I completely forgot about `operationId`.

You can use `schema.detail` to explicitly set `operationId` for each route like this.
<img width="395" alt="Screenshot 2566-05-06 at 16 52 43" src="https://user-images.githubusercontent.com/35027979/236617063-65dd6005-271b-4b7f-ab30-c5addc8a6ccb.png">

But I agree with setting automatically set `operationId`.

Please leave this open until I update the plugin to have automatically set `operationId`.

**Comment by kravetsone** [comment]
> Hi, thanks for pointing this out, I completely forgot about `operationId`.
> 
> You can use `schema.detail` to explicitly set `operationId` for each route like this.
> <img width="395" alt="Screenshot 2566-05-06 at 16 52 43" src="https://user-images.githubusercontent.com/35027979/236617063-65dd6005-271b-4b7f-ab30-c5addc8a6ccb.png">
> 
> But I agree with having automatically `operationId` set, would be convenient.
> 
> Please leave this open until I update the plugin to have automatically set `operationId`.

U already do it please close the issue
