### ISSUE TITLE
"Failed to load API definition."

### ISSUE THREAD

**Issue by Northernside** [elysiajs/elysia-swagger#6]
When trying to access the swagger url, it greets me with the following error:
<img width="552" alt="image" src="https://github.com/elysiajs/elysia-swagger/assets/60970791/ee4c54fd-7780-4deb-8431-8ac0b691c952">
And then when going to the direct JSON endpoint it shows me this in the browser:
```
Object.entries requires that input parameter not be null or undefined
```
Though, this only happens when being on the `experimental` version from `elysia`. I need that version though, because of the other routing bug in `latest` 👀
I don't know if I should report it here or in the other repository.

Example Code:
```js
import { Elysia } from "elysia";
import { swagger } from "@elysiajs/swagger";

export const app = new Elysia()
    .use(swagger({
        path: "/api/swagger",
        swagger: {
            info: {
                title: "e.bio API",
                version: "2.0.0-beta"
            }
        }
    }));

app.get("/api", () => {
    res.send("Hello World!");
});
```

Also, I don't know why, but the specified `title` and `version` aren't showing either within Swagger on `elysia@latest` since a few weeks.

**Comment by SaltyAom** [comment]
Got it, Elysia experimental has an internal breaking change for handling schema which I haven't updated the swagger plugin to match the latest version yet.

Updating to `@elysiajs/swagger: ^0.5.0-beta.0` should fix your problem.

**Comment by Northernside** [comment]
Thank you, this resolved my issue :)
Though, the other one with the title and version isn't. Should I open another issue?
<img width="567" alt="image" src="https://github.com/elysiajs/elysia-swagger/assets/60970791/039716b2-9886-46f3-8269-5daa26bf0528">

**Comment by Northernside** [comment]
Oh, and also it seems like the scheme isn't loading?
<img width="1431" alt="image" src="https://github.com/elysiajs/elysia-swagger/assets/60970791/cb28fa90-e93b-4972-94ff-e0647bda1ee5">

**Comment by Northernside** [comment]
Ohh sorry for the late response.
That's great, thank you! <3
