### ISSUE TITLE
Scalar options aren't applied

### ISSUE THREAD

**Issue by Mudbill** [elysiajs/elysia-swagger#94]
The `scalarConfig` object is ignored for the most part, instead of actually applying to the Scalar UI. As a result, almost all these options have no effect if you try to set them:

<img width="472" alt="image" src="https://github.com/elysiajs/elysia-swagger/assets/8832665/68b8ceba-1500-4452-98a4-9e873c4e4307">

[I checked the source code](https://github.com/elysiajs/elysia-swagger/blob/75a904b9864a9988e612a8e907f483ba1de98cf9/src/scalar/index.ts#L24C12-L24C12) and found that only the `customCss` and `spec.url` options are applied. 

Is this an oversight, or deliberate?

If I understand the docs correctly, it could be fixed with this:
```html
<script
    id="api-reference"
    data-url="${config.spec?.url}"
    data-configuration="${JSON.stringify(config)}"
></script>
```

Using:
- elysia-swagger: 0.8.3
- elysia: 0.8.9
- bun: 1.0.20

**Comment by marclave** [comment]
@Mudbill implemented in https://github.com/elysiajs/elysia-swagger/pull/96
